@authToken = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyIiwicm9sZSI6IlVTRVIiLCJpZCI6MiwiaWF0IjoxNzM1MTUxNzM0LCJleHAiOjE3MzUxNTQ3MzR9.s2_GQK_902VOJBdiT9hGCN2iKqpbo30tF-yMHas4DOpIC2L5Ip4QFOXnzA5LkLNxlCN-LBq4qXJ18bkHuBLaag

### GET ALL
GET http://localhost:9003/api/items
Authorization: Bearer {{authToken}}

### ADD ITEM
POST http://localhost:9003/api/items
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "Butter",
  "stock": 5
}

### UPDATE ITEM BY ID
PUT http://localhost:9003/api/items/1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "ButterX",
  "stock": 5
}

###
PUT http://localhost:9003/api/items/3/add/2
Authorization: Bearer {{authToken}}


###
PUT http://localhost:9003/api/items/3/remove/1

###
GET http://localhost:9003/api/items/carts/2
Authorization: Bearer {{authToken}}

