###
POST http://localhost:9003/api/item
Content-Type: application/json

{
  "name": "Butter",
  "stock": 2
}

###
GET http://localhost:9003/api/item
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTczNDU0MTM0MiwiZXhwIjoxNzM0NjI3NzQyfQ.3d5pT_dB5vKMC81SqPhYjpwaO8GT8JFL3lmTr53FP8abseR9XghiglKIz_T4LX9EpyRuTFP1w2bVmiNHdWZphw

###
PUT http://localhost:9003/api/item/3/add/1

###
PUT http://localhost:9003/api/item/3/remove/1
