
### LOGIN
POST http://localhost:9001/api/users/login
Content-Type: application/json

{
  "email": "user",
  "password": "user"
}

### REGISTER
POST http://localhost:9001/api/users/register
Content-Type: application/json

{
  "email": "user",
  "password": "user",
  "repeatedPassword": "user"
}


